---
title: "austraits values"
output: html_document
date: '2022-07-18'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(scatterplot3d)
```

```{r}
austraits <- read.csv("austraits-3.0.2/traits.csv", header = TRUE)
woodytraits <- read.csv("austraits-3.0.2/woodiness_2022.03.19.csv", header = TRUE)
sort(unique(austraits$trait_name))

austraits <- woodytraits %>% select(taxon_name, woodiness_recoded) %>% right_join(austraits) %>% mutate(ID = row_number())
```

```{r}
wood_density_vals <- austraits %>% 
  filter(trait_name == "wood_density", woodiness_recoded == "woody") %>% 
  mutate(ID = row_number())
leaf_n_vals <- austraits %>% 
  filter(trait_name == "leaf_N_per_area", woodiness_recoded == "woody") %>% 
  mutate(ID = row_number(),
         log_leaf_n = log(as.numeric(value)))
lma_vals <- austraits %>% 
  filter(trait_name == "specific_leaf_area", woodiness_recoded == "woody") %>%
  mutate(leaf_mass_area = 1/(as.numeric(value)),
         log_lma = log(leaf_mass_area))
seed_mass_vals <- austraits %>% 
  filter(trait_name == "seed_mass", woodiness_recoded == "woody", value < 100) %>% 
  mutate(ID = row_number(),
         log_sm = log(as.numeric(value)))

## 1/"specific_leaf_area" = LMA
```


Add plant data...
```{r}
leaf_n <- tibble(value = c(1.87, 5.0, 10.0), count = 1)
p1 = ggplot(leaf_n_vals, aes(log_leaf_n)) + 
  geom_histogram(binwidth = 0.05) + 
  geom_point(leaf_n, mapping = aes(log(value), count), col = "green") +
  xlim(-1.0, 2.5) + 
  xlab("log leaf N " ~ (g/m^2)) +
  theme_classic()

wood_density = tibble(value = c(0.3, 0.6, 0.8), count = 1)
p2 = ggplot(wood_density_vals, aes(as.numeric(value))) + 
  geom_histogram(binwidth = 0.01) + 
  geom_point(wood_density, mapping = aes(value, count), col = "green") +
  xlab("wood density " ~ (kg/m^3)) +
  theme_classic()

seed_mass <- tibble(value = c(1, 10, 20), count = 1)
p3 = ggplot(seed_mass_vals, aes(log10(as.numeric(value)))) + 
  geom_histogram(binwidth=0.05) +
  geom_point(seed_mass, mapping = aes(sqrt(value), count), col = "green") +
  xlab("sqrt seed mass (mg)") +
  theme_classic()

lma <- tibble(value = c(7.0, 24, 50), count = 1)
p4 = ggplot(lma_vals, aes(log_lma)) + 
  geom_histogram(binwidth = 0.05) + 
  geom_point(lma, mapping = aes(log(value), count), col = "green") +
  xlab("log leaf mass (mg/mm^2)") +
  theme_classic()

lma_plot + n_plot + wd_plot + sm_plot
```


```{r}
ggplot(seed_mass_vals, aes(sqrt(as.numeric(value)))) + 
  geom_histogram(binwidth = 0.05) +
  xlim(0, 2) +
  xlab("Seed Mass (mg)") +
  theme_classic()

ggplot(seed_mass_vals, aes(log_sm)) + 
  geom_histogram(binwidth = 0.05) +
  xlim(-3, 1) +
  xlab("Seed Mass (mg)") +
  theme_classic()
```

