---
title: "BAAD data"
output: html_document
date: '2022-07-29'
---

```{r}
library(plant)
library(dplyr)
library(tidyr)
library(ggplot2)
library(patchwork)
library(purrr)
```


```{r}

baad_data <- read.csv("baad_data.csv", header = TRUE)
baad_data_dictionary <- read.csv("baad_dictionary.csv", header = TRUE)
variables_names <- baad_data_dictionary$label

## "light environment" = light, "age" = age, "leaf area" = a.lf, "height" = h.t, "stem area at base/breast height/crown base" = a.stba/a.stbh/a.stbc, "dbh" = d.bh, "leaf mass" = m.lf, "total mass" = m.to, "wood density" = r.st, "leaf mass per area" = ma.ilf, "aboveground mass" = m.so, "leaf [nitrogen]" = n.lf

# 176 studies...
# 678 unique species...

abe1982 <- baad_data %>% filter(studyName == "Abe1981") %>% select_if(~ !any(is.na(.)))
str(abe1982)
ggplot(abe1982, aes(h.t, d.bh)) +
  geom_point() +
  theme_classic()

aiba2005 <- baad_data %>% filter(studyName == "Aiba2005") %>% select_if(~ !any(is.na(.)))
str(aiba2005)
ggplot(aiba2005, aes(h.t, d.bh)) +
  geom_point() +
  theme_classic()

albrektson1984 <- baad_data %>% filter(studyName == "Aiba2005") %>% select_if(~ !any(is.na(.)))
str(albrektson1984)
ggplot(albrektson1984, aes(h.t, d.bh)) +
  geom_point() +
  theme_classic()
```
dbh age
dbh la
# filter studies containing pairs of certain measurements and plot by study?
```{r}
# age vs LA values...

baad_data %>%
  ggplot(aes(age, a.lf, col = studyName)) +
  geom_point(show.legend = FALSE) +
  theme_classic()

baad_data %>%
  ggplot(aes(age, a.lf, col = studyName)) +
  geom_point(show.legend = FALSE) +
  geom_point(data = , )
  theme_classic() +
  xlim(0, 300) +
  ylim(0, 800)
```

