---
title: "Self-thinning lines"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, eval=FALSE}
remotes::install_github("traitecoevo/plant", branch = "develop", force = TRUE)
```

```{r load libraries}
library(plant)
library(dplyr)
library(tidyr)
library(ggplot2)
library(patchwork)
library(purrr)
source("R/grow_tidy_expand_totals function.R")
source("R/base_params function.R")
source("R/run_mypatch_edit function.R")
source("R/grow_tidy_plot function.R")
```

```{r activate logger}
plant_log_console()
```

## 1. Grow stand: high resolution + recruitment decay
```{r}
allsteps <- grow_tidy_expand_totals(oderel=1e-4, odeabs=1e-4, scheps=0.0001, rec_decay=5)

allsteps %>%
  ggplot(aes(time, individuals)) +
  geom_line()

allsteps %>%
  ggplot(aes(time, area_stem_av)) +
  geom_line()

```


## 2. Self-thinnning Plot
Average size over time. Get average size by dividing total by the sum of individuals per unit area

```{r}
# self-thinning line, stem area, diameter (same line as stem area), or height?
allsteps  %>% 
  filter(time > 0.2) %>%
  ggplot(aes(area_stem_av, individuals, col=time)) +
  geom_line() +
  scale_x_log10() +
  scale_y_log10() +
  theme_classic()

allsteps  %>% 
  filter(time > 0.2) %>%
  ggplot(aes(height_av, individuals, col=time)) +
  geom_line() +
  scale_x_log10() +
  scale_y_log10() +
  theme_classic()

# average stem area over time
allsteps %>%
  filter(time > 0.2) %>%
  ggplot(aes(time, area_stem_av)) +
  geom_line() +
  scale_x_log10() +
  scale_y_log10() +
  theme_classic()
  
# first wave of individuals captured
allsteps %>% filter(height > 0, time> 0, time<150) %>%
  ggplot(aes(time, individuals, colour=height)) +
  geom_line() + 
  theme_classic()

```


## Trait comparisons
```{r}

# 1. thick (0.24 LMA) vs thin (0.07 LMA) leaves - do other traits vary in response to LMA?
lma_values <- c(0.07, 0.24) %>% map_dfr(~grow_tidy_expand_totals(traits=trait_matrix(.x, "lma")), .id="run")

lma_values %>%
  filter(time > 0.2) %>%
  ggplot(aes(height_av, individuals, col=run)) + 
  geom_line() +
  scale_x_log10() +
  scale_y_log10() +
  theme_classic()

#density over time
lma_values %>%
  filter(time > 0.2) %>%
  ggplot(aes(time, individuals, col=run)) + 
  geom_line() +
  scale_x_log10() +
  scale_y_log10() +
  theme_classic()


# 2. HMAT
hmat_values <- c(15, 40) %>% map_dfr(~grow_tidy_expand_totals(traits=trait_matrix(.x, "hmat")), .id="run")
hmat_values %>%
  filter(time > 0.2) %>%
  ggplot(aes(area_stem_av, individuals, col=run)) + 
  geom_line() +
  scale_x_log10() +
  scale_y_log10() +
  theme_classic()
   

# 3. leaf N - narea, B_lf1? How should I implement different values?
blf1_values <- c(0.2, 0.6, 1) %>% map_dfr(~grow_tidy_expand_totals(B_lf1 = .x), .id="run")
blf1_values %>%
  filter(time > 0.2) %>%
  ggplot(aes(area_stem_av, individuals, col=run)) + 
  geom_line() +
  scale_x_log10() +
  scale_y_log10() +
  theme_classic()

narea_values <- c(0.00187, 0.003) %>% map_dfr(~grow_tidy_expand_totals(narea = .x), .id="run")
narea_values %>%
  filter(time > 0.2) %>%
  ggplot(aes(area_stem_av, individuals, col=run)) + 
  geom_line() +
  scale_x_log10() +
  scale_y_log10() +
  theme_classic()

```
